DEBUG_OBJ_DIR=obj/debug/${HOSTBITS}
RELEASE_OBJ_DIR=obj/release/${HOSTBITS}

CD_INCLUDE=${CD_HOME}/include

CD_BOOST_HOME=${CD_INCLUDE}/boost
CD_INC_BOOST=${CD_BOOST_HOME}

CD_LIBXML_HOME=${CD_INCLUDE}/libxml2
CD_INC_LIBXML=${CD_LIBXML_HOME}/libxml2

CD_BIN_DIR =${CD_HOME}/bin/${HOSTBITS}

CD_LIB_DIR =${CD_HOME}/libs/${HOSTBITS}
CD_CORE_LIBS= -lcd-base -lcd-infra

CD_STD_LIBS=-lrt -lpthread -lnsl -lstdc++ -latomic -lm -ldl -lxml2 -lz
CD_BOOST_LIBS=-lboost_system
CD_FEED_LIBS=-lcd-millenium

CD_INC_DIR =-I${CD_HOME} -I${CD_INCLUDE} -I${CD_INC_BOOST} -I${CD_INC_LIBXML}

CORE_C_FLAGS= -c -fPIC -std=c++11 
CORE_C_RELEASE_FLAGS= -O3 -minline-all-stringops -finline-limit=3006 
CORE_C_DEBUG_FLAGS= -g

#CORE_USER_FLAGS= -DASSERT_ENABLED -D__LATENCY__ -D__QWRITEREAD_LATENCY__ -D__NEXTREAD_LATENCY__ -D__MSG_LATENCY__ -D__PACKET_LATENCY__ -D__SUBMAP_LATENCY__ -D__ORDERMAP_LATENCY__ -D__ORDERPOOL_LATENCY__
CORE_USER_FLAGS= -D__LATENCY__ -D__MSG_LATENCY__

CFLAGS = ${CORE_C_FLAGS}
CC = gcc 
